name: quick_flash
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.3.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  flutter_inappwebview: ^6.1.0
  hive: ^2.2.3
  url_launcher: ^6.2.5
  app_tracking_transparency: ^2.0.6
  appsflyer_sdk: ^6.15.1
  hive_flutter: ^1.1.0
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.3
  flutter_asa_attribution: ^1.0.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    # SFProText
    - family: SFR
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
    - family: SFM
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
    - family: SFB
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
    - family: SFH
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Heavy.ttf